# Generated by Django 3.1.14 on 2022-09-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20220909_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemonentities', to='pokemon_entities.pokemon', verbose_name='Покемон'),
        ),
    ]
